import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./index.scss";
import MainLayout from "@/layouts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tess CV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MainLayout>{children} </MainLayout>
      </body>
    </html>
  );
}
